steps:
  # 1. Build the Frontend Docker Image
  # We use --build-arg to pass the backend URL into the React build process
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-frontend:$COMMIT_SHA'
      - '.'
    dir: 'pentest-frontend' # Tells Cloud Build to run this command inside the frontend folder

  # 2. Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-frontend:$COMMIT_SHA'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcp-frontend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-frontend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY