services:
  isha-db:
    image: postgres:16-alpine
    container_name: isha-db
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  isha-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: isha-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - isha-db

  frontend:
    build:
      context: ./frontend
    container_name: isha-frontend
    restart: unless-stopped
    depends_on:
      - isha-backend
    ports:
      - "5173:5173"
    environment:
      - VITE_GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
    volumes:
      # Mount frontend folder for Vite Hot Module Replacement (HMR)
      - ./frontend:/app
      # Prevent local node_modules from overwriting container node_modules
      - /app/node_modules

volumes:
  pgdata: