steps:
  # 1. Build the Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-backend:$COMMIT_SHA'
      - '.'

  # 2. Push the Docker Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-backend:$COMMIT_SHA'

  # 3. Dynamically append Cloud Build variables to our clean YAML file
  - name: 'ubuntu'
    dir: 'backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "" >> env.yaml
        echo "GCP_PROJECT_ID: '$PROJECT_ID'" >> env.yaml
        echo "COMMIT_SHA: '$SHORT_SHA'" >> env.yaml
        echo "BRANCH_NAME: '$BRANCH_NAME'" >> env.yaml
        echo "BUILD_ID: '$BUILD_ID'" >> env.yaml
        echo "REPO_NAME: '$REPO_NAME'" >> env.yaml

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: 'backend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gcp-backend'
      - '--image'
      - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-backend:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'gcp-backend-sa@gostcontrolpanel.iam.gserviceaccount.com'
      - '--network'
      - 'gcp-vpc'
      - '--subnet'
      - 'gcp-vpc-subnet'
      - '--vpc-egress'
      - 'private-ranges-only'
      - '--no-cpu-throttling'
      - '--min-instances'
      - '1'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '2'
      # Safely load the static variables from the new file
      - '--env-vars-file'
      - 'env.yaml'

images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/gcp-repo/gcp-backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
