"""Add Secure Notes

Revision ID: 017d044ee767
Revises: 1df6e22d0dfb
Create Date: 2026-07-11 17:14:37.369556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '017d044ee767'
down_revision: Union[str, Sequence[str], None] = '1df6e22d0dfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_notes',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_note', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_notes')
    # ### end Alembic commands ###