"""add duplicate_allowed filed to raw_asset

Revision ID: 154f28f08713
Revises: 791065da39cf
Create Date: 2026-07-07 08:01:37.050917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154f28f08713'
down_revision: Union[str, Sequence[str], None] = '791065da39cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_assets', sa.Column('duplicate_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_assets', 'duplicate_allowed')
    # ### end Alembic commands ###
