"""initial_setup

Revision ID: 791065da39cf
Revises: 
Create Date: 2026-07-06 10:52:54.907783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '791065da39cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('services_lanes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_concurrent_per_week', sa.Integer(), nullable=True),
    sa.Column('theme_color', sa.String(length=20), nullable=True),
    sa.Column('default_credits', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('default_duration_weeks', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('region_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('service_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_lane_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_goal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_lane_id'], ['services_lanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('base_capacity', sa.Float(), nullable=True),
    sa.Column('start_week', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_week', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_critical', sa.Integer(), nullable=True),
    sa.Column('confidentiality_rating', sa.Integer(), nullable=True),
    sa.Column('integrity_rating', sa.Integer(), nullable=True),
    sa.Column('availability_rating', sa.Integer(), nullable=True),
    sa.Column('facing_internet', sa.Boolean(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('service_forecast_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_forecast_id'], ['services_lanes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('service_lane_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('credits_per_week', sa.REAL(), nullable=True),
    sa.Column('duration_weeks', sa.REAL(), nullable=True),
    sa.Column('start_week', sa.Integer(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('stages', sa.Enum('NOT_PLANNED', 'SCHEDULED', 'IN_PROGRESS', 'STOPPED', 'DELETED', 'COMPLETED', 'ARCHIVED', name='teststages'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_lane_id'], ['services_lanes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_asset_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['raw_asset_id'], ['raw_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_asset_id', sa.UUID(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('service_forecast_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_assigned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_asset_id'], ['raw_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_forecast_id'], ['services_lanes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_asset_id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('allocated_credits', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_assets',
    sa.Column('test_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', 'asset_id')
    )
    # ### end Alembic commands ###
    users_stages_table = sa.table(
        'users',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.Column('github_id', sa.String),
        sa.Column('email', sa.String),
        sa.Column('name', sa.String),
        sa.Column('avatar_url', sa.String),
        sa.Column('role', sa.String),

    )
    op.bulk_insert(
        users_stages_table,
        [
            {'id': uuid.uuid4(), 'github_id': '99612766', 'email': 'vitobonetti@gmail.com', 'name': 'Isha',
             'avatar_url': 'https://avatars.githubusercontent.com/u/99612766?v=4', 'role': 'admin'},
        ]
    )

    asset_types_stages_table = sa.table(
        'asset_types',
        sa.Column('id', sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.Column('name', sa.String),
    )
    op.bulk_insert(
        asset_types_stages_table,
        [
            {'id': uuid.uuid4(), 'name': 'API'},
            {'id': uuid.uuid4(), 'name': 'Application'},
            {'id': uuid.uuid4(), 'name': 'Application/Database'},
            {'id': uuid.uuid4(), 'name': 'Backend AI Agent'},
            {'id': uuid.uuid4(), 'name': 'Analytic Platform'},
            {'id': uuid.uuid4(), 'name': 'Business Platform'},
            {'id': uuid.uuid4(), 'name': 'Cloud Storage'},
            {'id': uuid.uuid4(), 'name': 'Application/Database/Website'},
            {'id': uuid.uuid4(), 'name': 'Component'},
            {'id': uuid.uuid4(), 'name': 'Data Dashboard'},
            {'id': uuid.uuid4(), 'name': 'Data Source'},
            {'id': uuid.uuid4(), 'name': 'Data Visualization'},
            {'id': uuid.uuid4(), 'name': 'Database'},
            {'id': uuid.uuid4(), 'name': 'Database/Data Source'},
            {'id': uuid.uuid4(), 'name': 'Hardware'},
            {'id': uuid.uuid4(), 'name': 'Infrastructure'},
            {'id': uuid.uuid4(), 'name': 'Physical Devices'},
            {'id': uuid.uuid4(), 'name': 'Platform'},
            {'id': uuid.uuid4(), 'name': 'Search Engine'},
            {'id': uuid.uuid4(), 'name': 'SFTP Storage'},
            {'id': uuid.uuid4(), 'name': 'Web Application/Website'},
            {'id': uuid.uuid4(), 'name': 'Web Portal'},
        ]
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_assets')
    op.drop_table('test_history')
    op.drop_table('assignments')
    op.drop_table('assets')
    op.drop_table('asset_history')
    op.drop_table('tests')
    op.drop_table('raw_assets')
    op.drop_table('notifications')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('service_categories')
    op.drop_table('countries')
    op.drop_table('services_lanes')
    op.drop_table('regions')
    op.drop_table('locations')
    op.drop_table('asset_types')
    # ### end Alembic commands ###
