"""Add Target goal to Service Lane

Revision ID: d651d436369f
Revises: 017d044ee767
Create Date: 2026-07-13 18:32:27.795106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd651d436369f'
down_revision: Union[str, Sequence[str], None] = '017d044ee767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services_lanes', sa.Column('target_goal', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services_lanes', 'target_goal')
    # ### end Alembic commands ###
